name: Forerunner
description: Dynamically trigger templated buildkite pipelines on git diffs
author: https://github.com/staticfloat
configuration:
  properties:
    watch:
      type: array
    path_processor:
      type: string
    target:
      type: string
    target_type:
      type: string
  additionalProperties: false
